wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.37.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704797238.15858
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 23
      4: 3.11.6
      5: 0.16.1
      6: 4.37.0.dev0
      8:
      - 1
      - 5
      13: linux-x86_64
